# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 02ef9cf7e53c93efd284d1e0c2cd626703ca560012926fc2e1260f8003f50af3b22da6d297001cc9694f3979b718e1b198aea0a50d3e51ea715460ca71775a4e

test:
  secret_key_base: 35c949e865fb6ce88d51c54dcc4706861af2a721ff8520b8a1dd346272a36f1edb8b685d28a875682727ebccaa887b9a4ccb9354c4147f4e9594a9987035ce25

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
